apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: postgress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgress
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgress
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        ports:
        - containerPort: 5432
