apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis-deploy
 labels:
  app: redis
spec:
 replicas: 1
 template:
  metadata:
   name: redis-pod
   labels:
    app: redis
  spec:
   containers:
   - name: redis-container
     image: redis
     ports:
     - containerPort: 6379
 selector:
  matchLabels:
   app: redis 
