apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy.result-teja
 labels:
  app: deploy.result
spec:
 replicas: 3
 template:
  metadata:
   name: deploy-pod
   labels:
    app: deploy
  spec:
   containers:
   - name: result-container
     image: dockersamples/examplevotingapp_result
     ports:
     - containerPort: 80
 selector:
  matchLabels:
   app: deploy
