apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy-vote
 labels:
  app: deploy
spec:
 replicas: 3
 selector:
  matchLabels:
   app: voting.app
 template:
  metadata:
   name: voting.app-pod
   labels:
    app: voting.app
  spec:
   containers:
   - name: voting-container
     image: dockersamples/examplevotingapp_vote
     ports:
     - containerPort: 80
