apiVersion: v1
kind: Pod
metadata:
 name: voting.app-pod
 labels:
  app: voting.app
spec:
 containers:
 - name: voting-container
   image: dockersamples/examplevotingapp_vote
   ports:
   - containerPort: 80
  
